# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config

project_id = "cipherwill"

[api]
enabled = true

[db]
major_version = 15

[functions.daily-check-in]
verify_jwt = false
